// Named numeric constants for the visx-ported pattern geometry.
// Verbatim ports of the path formulas; each name describes a fraction.
// Fractional roles keep the tiles readable without changing any value.
const HALF_DIVISOR = 2;
const QUARTER_DIVISOR = 4;
const EIGHTH_DIVISOR = 8;
const THREE_QUARTER_FRACTION = 0.75;
const FIVE_QUARTER_FRACTION = 1.25;
const WAVE_CONTROL_NUMERATOR = 3;
const HEXAGON_TILE_SPAN = 3;
const TILE_ORIGIN = 0;
const DEFAULT_CIRCLE_RADIUS = 2;
const DEFAULT_HEXAGON_SIZE = 3;
const DEFAULT_PATTERN_SCALE = 1;
const DEFAULT_PATTERN_STROKE_WIDTH = 1;
const DOTS_STROKE_WIDTH = 0;
const DOT_RADIUS_MIN = 0.5;
const DOT_RADIUS_SCALE_FACTOR = 1.5;
const CIRCLE_RADIUS_SCALE_FACTOR = 2;

export {
  CIRCLE_RADIUS_SCALE_FACTOR,
  DEFAULT_CIRCLE_RADIUS,
  DEFAULT_HEXAGON_SIZE,
  DEFAULT_PATTERN_SCALE,
  DEFAULT_PATTERN_STROKE_WIDTH,
  DOT_RADIUS_MIN,
  DOT_RADIUS_SCALE_FACTOR,
  DOTS_STROKE_WIDTH,
  EIGHTH_DIVISOR,
  HALF_DIVISOR,
  HEXAGON_TILE_SPAN,
  FIVE_QUARTER_FRACTION,
  QUARTER_DIVISOR,
  THREE_QUARTER_FRACTION,
  TILE_ORIGIN,
  WAVE_CONTROL_NUMERATOR,
};
